site_name: 'TSE - Técnico Judiciário - Programação de Sistemas'
site_description: 'Documentação de Estudos para TSE - Técnico Judiciário - Programação de Sistemas'
site_url: https://acamposs.github.io/Estudos-TSE/
repo_url:
theme:
  name: 'material'
  palette:
    - scheme: default
      primary: 'grey'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mude para o modo escuro
    - scheme: slate
      primary: 'grey'
      toggle:
        icon: material/toggle-switch
        name: Mude para o modo claro
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - navigation.instant
    - navigation.tabs
    - toc.integrate
    - search.highlight
    - search.share
extra_css:
  - css/custom.css
extra_javascript:
  - javascripts/timer.js
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/js/all.min.js
nav:
  - Home: index.md
  - TSE:
      - TSE - Técnico Judiciário: concurso.md
  - Materiais de Estudo:
      - Português: portugues.md
      - Inglês: ingles.md
      - Direito Administrativo: direito_administrativo.md
      - Programação de Sistemas: programacao_sistemas.md
      - Banco de Dados: banco_dados.md
  - Gerenciamento:
      - Gerenciamento de Tempo: time_management.md
      - Lista de Tarefas: todo_list.md
markdown_extensions:
  - pymdownx.tasklist:
      clickable_checkbox: true  
  - def_list
  - attr_list
plugins:
  - search
  - git-revision-date-localized
